In [156]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [157]:
# Read the CSV file
df = pd.read_csv('SPY.csv')
print(df.columns)

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Day', 'Weekday',
       'Week', 'Month', 'Year'],
      dtype='object')

In [158]:
import pandas as pd
import matplotlib.pyplot as plt

# Load the data
file_path = "SPY.csv"
df = pd.read_csv(file_path)

# start to nov 2001 (dot com crash)
# not bad
# df = df.iloc[:2228]

# nov 01 to june 2009
# not bad
# df = df.iloc[2228:4135]

# june 2009 to april 2020
# ass
# df = df.iloc[4135:6862]

# april 2020 to most recent
# ass
# df = df.iloc[6862:]


# Convert the "Date" column to datetime
# df["Date"] = pd.to_datetime(df["Date"], format='%Y/%m/%d')

# # Sort the data by date in ascending order
# df = df.sort_values(by="Date")

# # Get the earliest and latest dates
# earliest_date = df["Date"].min()
# latest_date = df["Date"].max()

# print("Earliest Date:", earliest_date)
# print("Latest Date:", latest_date)

In [159]:
# start to nov 2001 (dot com crash)
# not bad
# df = df.iloc[:2228]

# nov 01 to june 2009
# not bad
# df = df.iloc[2228:4135]

# june 2009 to april 2020
# ass
# df = df.iloc[4135:6862]

df_section_1 = df.iloc[:2228]
df_section_2 = df.iloc[2228:4135]
df_section_3 = df.iloc[4135:6862]

In [160]:
# Adding SMA as part of the feature test
short_term_period = 20
medium_term_period = 50
long_term_period = 200

# Compute the SMAs
df_section_1['SMA_20'] = df_section_1['Close'].rolling(window=short_term_period).mean()
df_section_1['SMA_50'] = df_section_1['Close'].rolling(window=medium_term_period).mean()
df_section_1['SMA_200'] = df_section_1['Close'].rolling(window=long_term_period).mean()

df_section_1['EMA_10'] = df_section_1['Close'].ewm(span=10, adjust=False).mean()  # Short-term EMA
df_section_1['EMA_50'] = df_section_1['Close'].ewm(span=50, adjust=False).mean()  # Medium-term EMA
df_section_1['EMA_200'] = df_section_1['Close'].ewm(span=200, adjust=False).mean()  # Long-term EMA    

df_section_1 = df_section_1.dropna()

C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1553859596.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_1['SMA_20'] = df_section_1['Close'].rolling(window=short_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1553859596.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_1['SMA_50'] = df_section_1['Close'].rolling(window=medium_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1553859596.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_1['SMA_200'] = df_section_1['Close'].rolling(window=long_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1553859596.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_1['EMA_10'] = df_section_1['Close'].ewm(span=10, adjust=False).mean()  # Short-term EMA
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1553859596.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_1['EMA_50'] = df_section_1['Close'].ewm(span=50, adjust=False).mean()  # Medium-term EMA
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1553859596.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_1['EMA_200'] = df_section_1['Close'].ewm(span=200, adjust=False).mean()  # Long-term EMA

In [161]:
# Adding SMA as part of the feature test
short_term_period = 20
medium_term_period = 50
long_term_period = 200

# Compute the SMAs
df_section_2['SMA_20'] = df_section_2['Close'].rolling(window=short_term_period).mean()
df_section_2['SMA_50'] = df_section_2['Close'].rolling(window=medium_term_period).mean()
df_section_2['SMA_200'] = df_section_2['Close'].rolling(window=long_term_period).mean()

df_section_2['EMA_10'] = df_section_2['Close'].ewm(span=10, adjust=False).mean()  # Short-term EMA
df_section_2['EMA_50'] = df_section_2['Close'].ewm(span=50, adjust=False).mean()  # Medium-term EMA
df_section_2['EMA_200'] = df_section_2['Close'].ewm(span=200, adjust=False).mean()  # Long-term EMA    

df_section_2 = df_section_2.dropna()

C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1539512465.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_2['SMA_20'] = df_section_2['Close'].rolling(window=short_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1539512465.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_2['SMA_50'] = df_section_2['Close'].rolling(window=medium_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1539512465.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_2['SMA_200'] = df_section_2['Close'].rolling(window=long_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1539512465.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_2['EMA_10'] = df_section_2['Close'].ewm(span=10, adjust=False).mean()  # Short-term EMA
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1539512465.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_2['EMA_50'] = df_section_2['Close'].ewm(span=50, adjust=False).mean()  # Medium-term EMA
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1539512465.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_2['EMA_200'] = df_section_2['Close'].ewm(span=200, adjust=False).mean()  # Long-term EMA

In [162]:
# Adding SMA as part of the feature test
short_term_period = 20
medium_term_period = 50
long_term_period = 200

# Compute the SMAs
df_section_3['SMA_20'] = df_section_3['Close'].rolling(window=short_term_period).mean()
df_section_3['SMA_50'] = df_section_3['Close'].rolling(window=medium_term_period).mean()
df_section_3['SMA_200'] = df_section_3['Close'].rolling(window=long_term_period).mean()

df_section_3['EMA_10'] = df_section_3['Close'].ewm(span=10, adjust=False).mean()  # Short-term EMA
df_section_3['EMA_50'] = df_section_3['Close'].ewm(span=50, adjust=False).mean()  # Medium-term EMA
df_section_3['EMA_200'] = df_section_3['Close'].ewm(span=200, adjust=False).mean()  # Long-term EMA    

df_section_3 = df_section_3.dropna()

C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1804785841.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_3['SMA_20'] = df_section_3['Close'].rolling(window=short_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1804785841.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_3['SMA_50'] = df_section_3['Close'].rolling(window=medium_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1804785841.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_3['SMA_200'] = df_section_3['Close'].rolling(window=long_term_period).mean()
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1804785841.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_3['EMA_10'] = df_section_3['Close'].ewm(span=10, adjust=False).mean()  # Short-term EMA
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1804785841.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_3['EMA_50'] = df_section_3['Close'].ewm(span=50, adjust=False).mean()  # Medium-term EMA
C:\Users\ROG\AppData\Local\Temp/ipykernel_31072/1804785841.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_section_3['EMA_200'] = df_section_3['Close'].ewm(span=200, adjust=False).mean()  # Long-term EMA

In [163]:
feature_columns = ["Open", "High", "Low", "Close", "Volume", "SMA_20", "SMA_50", "SMA_200", "EMA_10", "EMA_50", "EMA_200"]

In [164]:

X_1 = df_section_1[feature_columns]

# Split data
train_size = int(X_1.shape[0] * 0.7)
val_size = int(X_1.shape[0] * 0.15)

# Initialize scaler
# scaler = RobustScaler()
scaler = MinMaxScaler()
# scaler = RobustScaler()

# Split data into train, validation, and test
temp_train = X_1[:train_size]
temp_val = X_1[train_size:train_size + val_size]
temp_test = X_1[train_size + val_size:]

temp_train = temp_train[feature_columns]
temp_val = temp_val[feature_columns]
temp_test = temp_test[feature_columns]

# Fit and transform for train, transform for validation and test
temp_train = scaler.fit_transform(temp_train)
temp_val = scaler.transform(temp_val)
temp_test = scaler.transform(temp_test)

# Convert NumPy arrays back to DataFrames
temp_train = pd.DataFrame(temp_train, columns=feature_columns)
temp_val = pd.DataFrame(temp_val, columns=feature_columns)
temp_test = pd.DataFrame(temp_test, columns=feature_columns)

# Concatenate the data
X_scaled1 = pd.concat([temp_train, temp_val, temp_test], axis=0)

# Split sequentially
X_train1 = X_scaled1[:train_size]
X_val1 = X_scaled1[train_size:train_size + val_size]
X_test1 = X_scaled1[train_size + val_size:]

# Print sizes to confirm
print(f"Train: {len(X_train1)}, Val: {len(X_val1)}, Test: {len(X_test1)}")

Train: 1420, Val: 304, Test: 305

In [165]:

X_2 = df_section_2[feature_columns]

# Split data
train_size = int(X_2.shape[0] * 0.7)
val_size = int(X_2.shape[0] * 0.15)

# Initialize scaler
# scaler = RobustScaler()
scaler = MinMaxScaler()
# scaler = RobustScaler()

# Split data into train, validation, and test
temp_train = X_2[:train_size]
temp_val = X_2[train_size:train_size + val_size]
temp_test = X_2[train_size + val_size:]

temp_train = temp_train[feature_columns]
temp_val = temp_val[feature_columns]
temp_test = temp_test[feature_columns]

# Fit and transform for train, transform for validation and test
temp_train = scaler.fit_transform(temp_train)
temp_val = scaler.transform(temp_val)
temp_test = scaler.transform(temp_test)

# Convert NumPy arrays back to DataFrames
temp_train = pd.DataFrame(temp_train, columns=feature_columns)
temp_val = pd.DataFrame(temp_val, columns=feature_columns)
temp_test = pd.DataFrame(temp_test, columns=feature_columns)

# Concatenate the data
X_scaled2 = pd.concat([temp_train, temp_val, temp_test], axis=0)

# Split sequentially
X_train2 = X_scaled2[:train_size]
X_val2 = X_scaled2[train_size:train_size + val_size]
X_test2 = X_scaled2[train_size + val_size:]

# Print sizes to confirm
print(f"Train: {len(X_train2)}, Val: {len(X_val2)}, Test: {len(X_test2)}")

Train: 1195, Val: 256, Test: 257

In [166]:

X_3 = df_section_3[feature_columns]

# Split data
train_size = int(X_3.shape[0] * 0.7)
val_size = int(X_3.shape[0] * 0.15)

# Initialize scaler
# scaler = RobustScaler()
scaler = MinMaxScaler()
# scaler = RobustScaler()

# Split data into train, validation, and test
temp_train = X_3[:train_size]
temp_val = X_3[train_size:train_size + val_size]
temp_test = X_3[train_size + val_size:]

temp_train = temp_train[feature_columns]
temp_val = temp_val[feature_columns]
temp_test = temp_test[feature_columns]

# Fit and transform for train, transform for validation and test
temp_train = scaler.fit_transform(temp_train)
temp_val = scaler.transform(temp_val)
temp_test = scaler.transform(temp_test)

# Convert NumPy arrays back to DataFrames
temp_train = pd.DataFrame(temp_train, columns=feature_columns)
temp_val = pd.DataFrame(temp_val, columns=feature_columns)
temp_test = pd.DataFrame(temp_test, columns=feature_columns)

# Concatenate the data
X_scaled3 = pd.concat([temp_train, temp_val, temp_test], axis=0)

# Split sequentially
X_train3 = X_scaled3[:train_size]
X_val3 = X_scaled3[train_size:train_size + val_size]
X_test3 = X_scaled3[train_size + val_size:]

# Print sizes to confirm
print(f"Train: {len(X_train3)}, Val: {len(X_val3)}, Test: {len(X_test3)}")

Train: 1769, Val: 379, Test: 380

In [167]:
X_scaled1.describe()

,Open,High,Low,Close,Volume,SMA_20,SMA_50,SMA_200,EMA_10,EMA_50,EMA_200
count,2029.000000,2029.000000,2029.000000,2029.000000,2029.000000,2029.000000,2029.000000,2029.000000,2029.000000,2029.000000,2029.000000
mean,0.544334,0.544037,0.538728,0.541089,0.196941,0.546385,0.549782,0.594232,0.546739,0.553936,0.576591
std,0.381922,0.385249,0.378860,0.383029,0.225841,0.395565,0.406608,0.464391,0.393080,0.410311,0.448018
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.170665,0.166318,0.170067,0.167504,0.020215,0.158117,0.153352,0.127703,0.161351,0.151174,0.128600
50%,0.557572,0.554338,0.549639,0.552771,0.136316,0.558194,0.557535,0.549652,0.560413,0.559808,0.540404
75%,0.912973,0.915776,0.904894,0.911314,0.300061,0.940034,0.943951,1.079390,0.933183,0.949512,1.049859
max,1.184398,1.198590,1.176710,1.183726,2.351418,1.184189,1.188546,1.301227,1.186388,1.199509,1.259943

In [168]:
X_scaled2.describe()

,Open,High,Low,Close,Volume,SMA_20,SMA_50,SMA_200,EMA_10,EMA_50,EMA_200
count,1708.000000,1708.000000,1708.000000,1708.000000,1708.000000,1708.000000,1708.000000,1708.000000,1708.000000,1708.000000,1708.000000
mean,0.534217,0.531309,0.530080,0.531745,0.435275,0.515142,0.514630,0.572388,0.520929,0.514947,0.544232
std,0.266973,0.269726,0.265601,0.266346,0.469427,0.288811,0.306523,0.340225,0.279833,0.304945,0.338428
min,-0.016744,-0.010729,-0.017607,-0.016504,0.000000,0.000000,0.000000,0.000000,-0.006423,0.000000,0.000000
25%,0.311900,0.304197,0.307464,0.306964,0.137379,0.266769,0.250440,0.303416,0.285252,0.252764,0.272277
50%,0.534088,0.528890,0.534204,0.531562,0.211624,0.514870,0.505703,0.569901,0.520584,0.505595,0.527028
75%,0.748610,0.750176,0.738222,0.747865,0.616521,0.758844,0.776481,0.848543,0.750050,0.769732,0.851524
max,1.054616,1.056296,1.039199,1.046347,3.239249,1.042559,1.039587,1.143620,1.044269,1.045119,1.108536

In [169]:
X_scaled3.describe()

,Open,High,Low,Close,Volume,SMA_20,SMA_50,SMA_200,EMA_10,EMA_50,EMA_200
count,2528.000000,2528.000000,2528.000000,2528.000000,2528.000000,2528.000000,2528.000000,2528.000000,2528.000000,2528.000000,2528.000000
mean,0.721391,0.723828,0.723182,0.722035,0.130829,0.720711,0.717044,0.743594,0.724833,0.723024,0.735924
std,0.463960,0.464526,0.460112,0.460841,0.110370,0.479775,0.487812,0.515978,0.474547,0.493484,0.514786
min,0.000000,0.000000,0.000000,0.000000,-0.024118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.266733,0.267644,0.272257,0.270800,0.055049,0.251552,0.248247,0.243963,0.260932,0.244078,0.235611
50%,0.707090,0.710256,0.708348,0.709569,0.101320,0.709084,0.706369,0.774149,0.708948,0.711886,0.763189
75%,1.122053,1.125655,1.114753,1.119605,0.173613,1.139159,1.116955,1.154265,1.143167,1.138687,1.143413
max,1.789669,1.791132,1.792567,1.786745,1.000000,1.788428,1.774046,1.757045,1.805155,1.794316,1.767095

In [170]:
X_scaled2

,Open,High,Low,Close,Volume,SMA_20,SMA_50,SMA_200,EMA_10,EMA_50,EMA_200
0,0.141385,0.126623,0.115238,0.105154,0.148470,0.099868,0.055435,0.250290,0.097539,0.080420,0.166705
1,0.097849,0.096027,0.098846,0.095289,0.175157,0.095339,0.053195,0.248290,0.091044,0.077662,0.164361
2,0.086405,0.076692,0.081228,0.070065,0.151851,0.088614,0.051273,0.246168,0.080901,0.073864,0.161686
3,0.078670,0.062837,0.078181,0.070380,0.143650,0.081339,0.049165,0.243902,0.072663,0.070230,0.159041
4,0.064356,0.049812,0.062948,0.062610,0.145782,0.074908,0.047141,0.241422,0.064435,0.066384,0.156314
...,...,...,...,...,...,...,...,...,...,...,...
252,0.270737,0.259669,0.270884,0.267156,0.676602,0.271744,0.216792,0.198208,0.269894,0.211341,0.239700
253,0.279599,0.275293,0.280458,0.277038,0.763940,0.272408,0.218643,0.195253,0.266856,0.211725,0.239187
254,0.273305,0.289484,0.280075,0.302190,1.018560,0.273572,0.220810,0.192794,0.269186,0.213239,0.239033
255,0.300278,0.290396,0.301774,0.299110,0.598787,0.273454,0.222537,0.190272,0.270503,0.214553,0.238837
256,0.304646,0.297948,0.305987,0.310147,0.602174,0.272382,0.224348,0.187671,0.273693,0.216319,0.238799